version: '2'

services:
  influx:
    image: influxdb:0.13
    ports:
      - 8083:8083
      - 8086:8086
      - 8090:8090
      - 8099:8099
    environment:
      PRE_CREATE_DB: "influxdb"
  fluent:
    build: ./fluent
    ports:
      - 24224:24224
    volumes:
      - ./fluent/data:/fluentd/log
      - ./fluent/etc:/fluentd/etc
    links:
      - es:es
  es:
    image: elasticsearch:2.3.4
    ports:
      - 9200:9200
    # environment:
    #   ELASTICSEARCH_USER: admin
    #   ELASTICSEARCH_PASS: mypass
  kibana:
    image: kibana:4.5.2
    ports:
      - 5601:5601
    links:
      - es:es
    environment:
      - ELASTICSEARCH_URL=http://es:9200
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    links:
      - influx:influx
    environment:
      INFLUXDB_HOST: influx
      INFLUXDB_PORT: 8086
      INFLUXDB_NAME: influxdb
      INFLUXDB_USER: root
      INFLUXDB_PASS: root
      ELASTICSEARCH_HOST: es
      ELASTICSEARCH_PORT: 9200
      ELASTICSEARCH_USER: admin
      ELASTICSEARCH_PASS: mypass
      GF_SERVER_ROOT_URL: http://docker
      GF_SECURITY_ADMIN_PASSWORD: secret
